version: "3.3"

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    # install requirements.txt
    
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://db_user:db_pass@db/db_name
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=db_name

volumes:
  postgres_data:

networks:
  default: 
    name: logistic_system